# Python CircleCI 2.0 configuration file
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: theholyatom/mircroblog
    docker:
      #- image: circleci/buildpack-deps:stretch
      - image: circleci/python:3.7
jobs:
  build:
    executor: docker-publisher
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - setup_remote_docker
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install pylint
            pip install py
            pip install pytest
            pip install coverage
            pip install -r requirements.txt
            make install
            make validate
            make exec-tests
            python3 -m coverage report  --rcfile=.coveragerc
            make clean-cov
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest -f docker/Dockerfile_prod.yml .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
    build-tags:
      jobs:
        - build:
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
        - publish-tag:
            requires:
              - build
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/