# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: theholyatom/mircroblog
    docker:
      #- image: circleci/buildpack-deps:stretch
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - setup_remote_docker
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install pylint
            pip install py
            pip install pytest
            pip install coverage
            pip install -r requirements.txt
            make install
            validate exec-tests
            python3 -m coverage report  --rcfile=.coveragerc
            make clean-cov
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master